default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres #${DB_HOST}
      user: airflow #${DB_USER}
      password: airflow #${DB_PASSWORD}
      port: 5432
      dbname: airflow #${DB_NAME}
      schema: dbt_pokemon